version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - NODE_ENV=production
    volumes:
      - ./public:/usr/src/app/public
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data: